# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         UML-Sequence
version:      0.08
version_from: lib/UML/Sequence.pm
installdirs:  site
requires:
    GD:                            2.30
    Test::More:                    0
    XML::DOM:                      1.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
